### ISSUE TITLE
你好有问题求教。

### ISSUE THREAD

**Issue by XiangfuLiu** [bing-framework/Bing.EasyPrint#4]
可以直接添加QQ群么，或者能否提供一个操作说明，谢谢

**Comment by jianxuanbing** [comment]
单元测试已经有完整的测试用例了。
主要是生成16进制的字符串，用于发送到热敏打印机进行打印。
单元测试中，是直接通过USB连接打印机打印的。

**Comment by XiangfuLiu** [comment]
好的。感谢你的回复与帮助，我已经通过你提供的方法解决了我的问题，感谢你的分享
