### ISSUE TITLE
怎么使用呢？

### ISSUE THREAD

**Issue by shiqw** [bing-framework/Bing.EasyPrint#5]
请问这个怎么使用，都看不到跟设备连接的代码

**Comment by jianxuanbing** [comment]
单元测试是基于 USB 连接的方式连接 小票打印机的，主要将指令生成后，发送到小票打印机。
实际场景是通过 APP 通过蓝牙的方式，进行打印。
该类库主要是用于 指令的调用，减少手扣 指令的方式。

**Comment by shiqw** [comment]
你好！你的邮件我已收到

**Comment by shiqw** [comment]
玄总，如果我想通过ip连接发送打印内容，还有使用模板，要怎么做呢？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "bing-framework/Bing.EasyPrint"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年10月9日(星期一) 下午5:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [bing-framework/Bing.EasyPrint] 怎么使用呢？ (Issue #5)





 
单元测试是基于 USB 连接的方式连接 小票打印机的，主要将指令生成后，发送到小票打印机。
 实际场景是通过 APP 通过蓝牙的方式，进行打印。
 该类库主要是用于 指令的调用，减少手扣 指令的方式。

**Comment by jianxuanbing** [comment]
> 玄总，如果我想通过ip连接发送打印内容，还有使用模板，要怎么做呢？
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "bing-framework/Bing.EasyPrint" ***@***.***&gt;; 发送时间:&nbsp;2023年10月9日(星期一) 下午5:10 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [bing-framework/Bing.EasyPrint] 怎么使用呢？ (Issue #5) 单元测试是基于 USB 连接的方式连接 小票打印机的，主要将指令生成后，发送到小票打印机。 实际场景是通过 APP 通过蓝牙的方式，进行打印。 该类库主要是用于 指令的调用，减少手扣 指令的方式。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

是向指定IP发送请求么？那你实际上就得在那里弄个socket，做个下发操作，然后那个IP通过USB来连接打印机

**Comment by shiqw** [comment]
你好！你的邮件我已收到

**Comment by shiqw** [comment]
谢谢玄总解答，那怎么使用模版进行构建打印内容，里面没有用例



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月5日(周二) 下午5:19
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [bing-framework/Bing.EasyPrint] 怎么使用呢？ (Issue #5)




  
玄总，如果我想通过ip连接发送打印内容，还有使用模板，要怎么做呢？
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "bing-framework/Bing.EasyPrint" @.&gt;; 发送时间:&nbsp;2023年10月9日(星期一) 下午5:10 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [bing-framework/Bing.EasyPrint] 怎么使用呢？ (Issue #5) 单元测试是基于 USB 连接的方式连接 小票打印机的，主要将指令生成后，发送到小票打印机。 实际场景是通过 APP 通过蓝牙的方式，进行打印。 该类库主要是用于 指令的调用，减少手扣 指令的方式。 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: @.***&gt;
  
是向指定IP发送请求么？那你实际上就得在那里弄个socket，做个下发操作，然后那个IP通过USB来连接打印机
